## 필요한 파일 불러오기

In [26]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np

### 붓꽃 데이터 세트 로딩

In [5]:
iris=load_iris()

### iris.data는 iris data 세트에서 feature만으로 된 데이터를 numpy로 가짐

In [6]:
iris_data=iris.data

### iris.target은 붓꽃 데이터 세트에서 레이블 값을 numpy로 가짐

In [8]:
iris_label=iris.target

In [9]:
print("iris target값:",iris_label)
print("iris target명:", iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


### 데이터세트로 변환하기

In [10]:
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

### 학습용, 예측용 데이터 나누기

In [11]:
X_train,X_test,y_train, y_test=train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

### DecisionTreeClassifier 객체 생성

In [12]:
dt_clf=DecisionTreeClassifier(random_state=11)

### 학습 수행

In [13]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

### 학습 기반으로 예측 수행

In [14]:
pred=dt_clf.predict(X_test)

### 예측 정확도 측정

In [15]:
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도:0.9333


### 데이터 세트의 키값 확인하기

In [20]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


### 키들이 가리키는 값을 출력하기

In [23]:
print('\n feature_names의 type:',type(iris_data.feature_names))
print('feature_names의 shape:',len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:',type(iris_data.target_names))
print('target_names의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:',type(iris_data.data))
print('data의 shape:',len(iris_data.data.shape))
print(iris_data['data'])

print('\n target_names의 type:',type(iris_data.target))
print('target_names의 shape:',len(iris_data.target.shape))
print(iris_data.target)


 feature_names의 type: <class 'list'>
feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: 2
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3

### K 폴드 교차 검증

In [32]:
features=iris.data
label=iris.target
kfold=KFold(n_splits=5)
dt_clf=DecisionTreeClassifier(random_state=156)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [34]:
n_iter=0
for train_index,test_index in kfold.split(features):
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    n_iter+=1
    #반복시마다 정확도 측정
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n{0} 교차 검증 정확도:{1},학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
    print('#{0} 검증 세터 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    
    #평균 정확도 계산
    print('\n##평균 검증 정확도:',np.mean(cv_accuracy))


1 교차 검증 정확도:1.0,학습 데이터 크기:120, 검증 데이터 크기:30
#1 검증 세터 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

##평균 검증 정확도: 1.0

2 교차 검증 정확도:0.9667,학습 데이터 크기:120, 검증 데이터 크기:30
#2 검증 세터 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

##평균 검증 정확도: 0.98335

3 교차 검증 정확도:0.8667,학습 데이터 크기:120, 검증 데이터 크기:30
#3 검증 세터 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

##평균 검증 정확도: 0.9444666666666667

4 교차 검증 정확도:0.9333,학습 데이터 크기:120, 검증 데이터 크기:30
#4 검증 세터 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

##평균 검증 정확도: 0.941675

5 교차 검증 정확도:0.7333,학습 데이터 크기:120, 검증 데이터 크기:30
#5 검증 세터 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##평균 검증 정확도: 0.9
